const fs = require("fs");
const path = require("path");

const root = process.cwd();
const speciesPath = path.join(root, "reference", "pokeemerald-expansion", "include", "constants", "species.h");
const outTsPath = path.join(root, "src", "features", "game", "config", "referenceExtraSpecies.ts");
const outMdPath = path.join(root, "reference", "pokeemerald-expansion", "SPECIAL_SPECIES_RULES_ZH.md");

function inferRule(name) {
  if (name.includes("_MEGA")) {
    return {
      ruleKey: "BATTLE_MEGA",
      ruleZh: "Mega形态",
      requiresSpecialFlow: true,
      requiresItem: true,
      note: "通常需要对应 Mega 石 + 钥石，并在战斗中触发。",
    };
  }
  if (name.includes("_GMAX")) {
    return {
      ruleKey: "BATTLE_DYNAMAX_GMAX",
      ruleZh: "极巨/超极巨",
      requiresSpecialFlow: true,
      requiresItem: false,
      note: "需要极巨化战斗流程（含极巨因子/极巨点环境）。",
    };
  }
  if (name.includes("_TERA") || name.includes("TERASTAL") || name.includes("STELLAR")) {
    return {
      ruleKey: "BATTLE_TERA",
      ruleZh: "太晶化形态",
      requiresSpecialFlow: true,
      requiresItem: false,
      note: "需要太晶化战斗流程触发。",
    };
  }
  if (name.includes("_TOTEM")) {
    return {
      ruleKey: "EVENT_ONLY",
      ruleZh: "霸主/剧情特化形态",
      requiresSpecialFlow: true,
      requiresItem: false,
      note: "通常为剧情或特殊遭遇，不是常规随机形态。",
    };
  }
  if (name.includes("_PALDEA_") || name.endsWith("_PALDEA") || name.includes("_ALOLA") || name.includes("_GALAR") || name.includes("_HISUI")) {
    return {
      ruleKey: "DIRECT",
      ruleZh: "地区形态",
      requiresSpecialFlow: false,
      requiresItem: false,
      note: "可作为普通形态直接入池。",
    };
  }
  if (name.startsWith("SPECIES_UNOWN_") || name.startsWith("SPECIES_SCATTERBUG_") || name.startsWith("SPECIES_SPEWPA_")) {
    return {
      ruleKey: "DIRECT",
      ruleZh: "图鉴字母/花纹形态",
      requiresSpecialFlow: false,
      requiresItem: false,
      note: "可直接作为差异形态入池。",
    };
  }
  if (
    name.includes("WISHIWASHI_SCHOOL")
    || name.includes("MIMIKYU_BUSTED")
    || name.includes("PALAFIN_HERO")
    || name.includes("EISCUE_NOICE")
    || name.includes("MORPEKO_HANGRY")
    || name.includes("AEGISLASH_BLADE")
    || name.includes("DARMANITAN_ZEN")
    || name.includes("CASTFORM_")
    || name.includes("ZEN_MODE")
  ) {
    return {
      ruleKey: "BATTLE_ABILITY",
      ruleZh: "战斗触发形态",
      requiresSpecialFlow: true,
      requiresItem: false,
      note: "依赖特性/天气/血量等战斗条件，不建议作为初始形态直接发放。",
    };
  }
  if (
    name.includes("ZACIAN_CROWNED")
    || name.includes("ZAMAZENTA_CROWNED")
    || name.includes("GIRATINA_ORIGIN")
    || name.includes("OGERPON_")
  ) {
    return {
      ruleKey: "HOLD_ITEM",
      ruleZh: "携带道具形态",
      requiresSpecialFlow: false,
      requiresItem: true,
      note: "通常需要特定携带道具来维持或切换形态。",
    };
  }
  return {
    ruleKey: "DIRECT",
    ruleZh: "可直接形态",
    requiresSpecialFlow: false,
    requiresItem: false,
    note: "默认按可直接入池处理，建议后续逐项验证。",
  };
}

function main() {
  const text = fs.readFileSync(speciesPath, "utf8");
  const lines = text.split(/\r?\n/);
  const entries = [];

  for (const line of lines) {
    const m = line.match(/^#define\s+(SPECIES_[A-Z0-9_]+)\s+([0-9]+)\s*$/);
    if (!m) continue;
    const name = m[1];
    const id = Number(m[2]);
    if (id <= 1025 || id >= 5000) continue;
    const inferred = inferRule(name);
    entries.push({
      id,
      name,
      ...inferred,
    });
  }

  entries.sort((a, b) => a.id - b.id);

  const tsLines = [];
  tsLines.push("// Auto-generated by scripts/generate_reference_extra_species.cjs");
  tsLines.push("export interface ReferenceExtraSpeciesEntry {");
  tsLines.push("  id: number;");
  tsLines.push("  name: string;");
  tsLines.push("  ruleKey: 'DIRECT' | 'HOLD_ITEM' | 'BATTLE_MEGA' | 'BATTLE_DYNAMAX_GMAX' | 'BATTLE_TERA' | 'BATTLE_ABILITY' | 'EVENT_ONLY';");
  tsLines.push("  ruleZh: string;");
  tsLines.push("  requiresSpecialFlow: boolean;");
  tsLines.push("  requiresItem: boolean;");
  tsLines.push("  note: string;");
  tsLines.push("}");
  tsLines.push("");
  tsLines.push("export const REFERENCE_EXTRA_SPECIES: ReferenceExtraSpeciesEntry[] = [");
  for (const entry of entries) {
    tsLines.push(
      `  { id: ${entry.id}, name: '${entry.name}', ruleKey: '${entry.ruleKey}', ruleZh: '${entry.ruleZh}', requiresSpecialFlow: ${entry.requiresSpecialFlow}, requiresItem: ${entry.requiresItem}, note: '${entry.note}' },`
    );
  }
  tsLines.push("];");
  tsLines.push("");

  const grouped = new Map();
  for (const entry of entries) {
    if (!grouped.has(entry.ruleZh)) grouped.set(entry.ruleZh, []);
    grouped.get(entry.ruleZh).push(entry);
  }

  const mdLines = [];
  mdLines.push("# 额外形态/特殊种规则对照（基于 pokeemerald-expansion）");
  mdLines.push("");
  mdLines.push("- 数据源：`reference/pokeemerald-expansion/include/constants/species.h`");
  mdLines.push("- 统计范围：`ID 1026 ~ 1572`（相对本项目 1~1025 的额外段）");
  mdLines.push(`- 统计时间：${new Date().toLocaleString("zh-CN", { hour12: false })}`);
  mdLines.push(`- 总计：${entries.length}`);
  mdLines.push("");
  mdLines.push("## 核心结论");
  mdLines.push("");
  mdLines.push("1. `BATTLE_MEGA / BATTLE_DYNAMAX_GMAX / BATTLE_TERA / BATTLE_ABILITY / EVENT_ONLY` 这些类型需要特殊战斗流程或剧情机制，不建议直接作为普通租借池形态。");
  mdLines.push("2. `HOLD_ITEM` 需要携带特定道具才能稳定表现为对应形态（例如 Zacian/Zamazenta 冠之形态、Ogerpon 面具形态等）。");
  mdLines.push("3. `DIRECT` 可作为当前项目优先补充的“可直接入池形态”。");
  mdLines.push("");

  for (const [groupName, groupEntries] of [...grouped.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    mdLines.push(`## ${groupName}（${groupEntries.length}）`);
    mdLines.push("");
    mdLines.push("| ID | 常量 | 规则键 | 是否需特殊流程 | 是否需道具 | 备注 |");
    mdLines.push("|---:|---|---|---|---|---|");
    for (const entry of groupEntries) {
      mdLines.push(
        `| ${entry.id} | \`${entry.name}\` | \`${entry.ruleKey}\` | ${entry.requiresSpecialFlow ? "是" : "否"} | ${entry.requiresItem ? "是" : "否"} | ${entry.note} |`
      );
    }
    mdLines.push("");
  }

  fs.writeFileSync(outTsPath, `${tsLines.join("\n")}\n`, "utf8");
  fs.writeFileSync(outMdPath, `${mdLines.join("\n")}\n`, "utf8");

  const summary = {};
  for (const entry of entries) {
    summary[entry.ruleKey] = (summary[entry.ruleKey] || 0) + 1;
  }
  console.log(`GeneratedEntries=${entries.length}`);
  console.log(`Summary=${JSON.stringify(summary)}`);
}

main();
