export const TYPE_CHART: Record<string, Record<string, number>> = {
  normal: { rock: 0.5, ghost: 0, steel: 0.5 },
  fire: { fire: 0.5, water: 0.5, grass: 2, ice: 2, bug: 2, rock: 0.5, dragon: 0.5, steel: 2 },
  water: { fire: 2, water: 0.5, grass: 0.5, ground: 2, rock: 2, dragon: 0.5 },
  electric: { water: 2, electric: 0.5, grass: 0.5, ground: 0, flying: 2, dragon: 0.5 },
  grass: { fire: 0.5, water: 2, grass: 0.5, poison: 0.5, ground: 2, flying: 0.5, bug: 0.5, rock: 2, dragon: 0.5, steel: 0.5 },
  ice: { fire: 0.5, water: 0.5, grass: 2, ice: 0.5, ground: 2, flying: 2, dragon: 2, steel: 0.5 },
  fighting: { normal: 2, ice: 2, poison: 0.5, flying: 0.5, psychic: 0.5, bug: 0.5, rock: 2, ghost: 0, dark: 2, steel: 2, fairy: 0.5 },
  poison: { grass: 2, poison: 0.5, ground: 0.5, rock: 0.5, ghost: 0.5, steel: 0, fairy: 2 },
  ground: { fire: 2, electric: 2, grass: 0.5, poison: 2, flying: 0, bug: 0.5, rock: 2, steel: 2 },
  flying: { electric: 0.5, grass: 2, fighting: 2, bug: 2, rock: 0.5, steel: 0.5 },
  psychic: { fighting: 2, poison: 2, psychic: 0.5, dark: 0, steel: 0.5 },
  bug: { fire: 0.5, grass: 2, fighting: 0.5, poison: 0.5, flying: 0.5, psychic: 2, ghost: 0.5, dark: 2, steel: 0.5, fairy: 0.5 },
  rock: { fire: 2, ice: 2, fighting: 0.5, ground: 0.5, flying: 2, bug: 2, steel: 0.5 },
  ghost: { normal: 0, psychic: 2, ghost: 2, dark: 0.5 },
  dragon: { dragon: 2, steel: 0.5, fairy: 0 },
  dark: { fighting: 0.5, psychic: 2, ghost: 2, dark: 0.5, fairy: 0.5 },
  steel: { fire: 0.5, water: 0.5, electric: 0.5, ice: 2, rock: 2, steel: 0.5, fairy: 2 },
  fairy: { fire: 0.5, fighting: 2, poison: 0.5, dragon: 2, dark: 2, steel: 0.5 },
};

export const TYPE_ZH: Record<string, string> = {
  normal: '一般',
  fire: '火',
  water: '水',
  electric: '电',
  grass: '草',
  ice: '冰',
  fighting: '格斗',
  poison: '毒',
  ground: '地面',
  flying: '飞行',
  psychic: '超能力',
  bug: '虫',
  rock: '岩石',
  ghost: '幽灵',
  dragon: '龙',
  dark: '恶',
  steel: '钢',
  fairy: '妖精',
};

export const GENERATIONS = [
  { id: 1, name: '第一世代', region: '关都', range: [1, 151] },
  { id: 2, name: '第二世代', region: '城都', range: [152, 251] },
  { id: 3, name: '第三世代', region: '丰缘', range: [252, 386] },
  { id: 4, name: '第四世代', region: '神奥', range: [387, 493] },
  { id: 5, name: '第五世代', region: '合众', range: [494, 649] },
  { id: 6, name: '第六世代', region: '卡洛斯', range: [650, 721] },
  { id: 7, name: '第七世代', region: '阿罗拉', range: [722, 809] },
  { id: 8, name: '第八世代', region: '伽勒尔', range: [810, 898] },
  { id: 9, name: '第九世代', region: '帕底亚', range: [899, 1025] },
];

export const NATURES = [
  { name: 'adamant', zhName: '固执', plus: 'attack', minus: 'spAtk' },
  { name: 'bashful', zhName: '害羞', plus: '', minus: '' },
  { name: 'bold', zhName: '大胆', plus: 'defense', minus: 'attack' },
  { name: 'brave', zhName: '勇敢', plus: 'attack', minus: 'speed' },
  { name: 'calm', zhName: '温和', plus: 'spDef', minus: 'attack' },
  { name: 'careful', zhName: '慎重', plus: 'spDef', minus: 'spAtk' },
  { name: 'docile', zhName: '坦率', plus: '', minus: '' },
  { name: 'gentle', zhName: '温顺', plus: 'spDef', minus: 'defense' },
  { name: 'hardy', zhName: '勤奋', plus: '', minus: '' },
  { name: 'hasty', zhName: '急躁', plus: 'speed', minus: 'defense' },
  { name: 'impish', zhName: '淘气', plus: 'defense', minus: 'spAtk' },
  { name: 'jolly', zhName: '爽朗', plus: 'speed', minus: 'spAtk' },
  { name: 'lax', zhName: '乐天', plus: 'defense', minus: 'spDef' },
  { name: 'lonely', zhName: '怕寂寞', plus: 'attack', minus: 'defense' },
  { name: 'mild', zhName: '慢吞吞', plus: 'spAtk', minus: 'defense' },
  { name: 'modest', zhName: '内敛', plus: 'spAtk', minus: 'attack' },
  { name: 'naive', zhName: '天真', plus: 'speed', minus: 'spDef' },
  { name: 'naughty', zhName: '顽皮', plus: 'attack', minus: 'spDef' },
  { name: 'quiet', zhName: '冷静', plus: 'spAtk', minus: 'speed' },
  { name: 'quirky', zhName: '离奇', plus: '', minus: '' },
  { name: 'rash', zhName: '马虎', plus: 'spAtk', minus: 'spDef' },
  { name: 'relaxed', zhName: '悠闲', plus: 'defense', minus: 'speed' },
  { name: 'sassy', zhName: '自大', plus: 'spDef', minus: 'speed' },
  { name: 'serious', zhName: '认真', plus: '', minus: '' },
  { name: 'timid', zhName: '胆小', plus: 'speed', minus: 'attack' },
];
