const uiStrings: Record<string, Record<string, string>> = {
  'zh-hans': {
    stage: '关卡',
    switch: '出战',
    info: '详情',
    selectMove: '选择技能',
    back: '返回',
    victory: '胜利！',
    chooseReward: '选择一项奖励以继续你的冒险',
    viewTeam: '查看我的队伍',
    randomRewards: '随机奖励',
    getItem: '获得道具',
    learnMove: '学习新技能',
    learnMoveDesc: '让队伍中的一只宝可梦学习一个新技能',
    evolutionReward: '宝可梦进化',
    evolutionRewardDesc: '让队伍中的一只宝可梦进化到下一阶段',
    specialReward: '特殊奖励',
    joinTeam: '加入队伍',
    selectThis: '选择此项',
    mysteryShop: '神秘商店 (使用金币购买)',
    insufficientCoins: '金币不足',
    buyItem: '购买道具',
    teamFull: '队伍已满！',
    replacePartner: '选择一只宝可梦进行替换，以加入新的伙伴',
    power: '威力',
    accuracy: '命中',
    pp: 'PP',
    nature: '性格',
    ability: '特性',
    none: '无',
    stats: '能力值',
    currentMoves: '当前技能',
    base: '种族',
    iv: '个体',
    physical: '物理',
    special: '特攻',
    status: '变化',
    confirm: '确认',
    cancel: '取消',
    battleLog: '战斗记录',
    hp: 'HP',
    attack: '攻击',
    defense: '防御',
    spAtk: '特攻',
    spDef: '特防',
    speed: '速度',
    catchSuccess: '捕捉成功！获得了 {coins} 金币！',
    battleVictory: '战斗胜利！获得了 {coins} 金币！',
    selectToLearn: '选择一只宝可梦来学习新的力量',
    retrievingMoves: '正在检索可学习的技能...',
    replaceWhichMove: '替换哪个技能？',
    alreadyKnows4: '{name} 已经学会了4个技能。',
    selectOldToReplace: '请选择一个旧技能来替换为 {move}。',
    movesCount: '{count}/4 技能',
    learnMoveBtn: '学习技能',
    cancelReplace: '取消替换',
    searchingPokemon: '正在寻找宝可梦...',
    battleHistory: '对战历史',
    chooseStarter: '选择你的初始伙伴',
    chooseStarterDesc: '从这三只随机宝可梦中选择一只开始你的冒险',
    startingMoves: '初始技能',
    viewDetails: '查看详情',
    iChooseYou: '就决定是你了！',
    gymLeaderSent: '道馆馆主 派出了 {name}！',
    wildPokemonAppeared: '野生的 {name} 出现了！',
    youUsed: '你使用了 {name}！',
    cannotCatchGym: '不能捕捉道馆馆主的宝可梦！',
    catching: '正在捕捉...',
    catchSuccessMsg: '成功捕捉了 {name}！',
    joinedTeam: '{name} 已加入你的队伍！',
    brokeFree: '{name} 挣脱了！',
    withdrew: '你收回了 {name}！',
    sentOut: '你派出了 {name}！',
    usedMove: '{name} 使用了 {move}！',
    superEffective: '这一击效果绝佳！',
    notVeryEffective: '这一击收效甚微...',
    noEffect: '似乎没有效果...',
    causedDamage: '{name} 造成了 {damage} 点伤害。',
    fainted: '{name} 倒下了！',
    enemyUsedMove: '对手的 {name} 使用了 {move}！',
    enemyCausedDamage: '对手的 {name} 造成了 {damage} 点伤害。',
    noRecords: '尚无记录',
    rogueJourney: 'PokeFactory 之旅：在无尽的挑战中生存',
    startBattle: '开始对战',
    selectRegion: '选择你的冒险地区',
    nextStep: '下一步：选择等级',
    setDifficulty: '设定初始挑战难度',
    startAdventure: '开启冒险之旅',
    thinking: '对手正在思考...',
    commandPhase: '指令阶段',
    whatToDo: '该怎么办呢？',
    atkUp: '攻击↑',
    defUp: '防御↑',
    battle: '战斗',
    bag: '背包',
    pokemon: '宝可梦',
    run: '逃跑',
    myBag: '我的背包',
    myTeam: '我的队伍',
    bagEmpty: '背包空空如也',
    backToMoves: '返回选择技能',
    evolution: '进化',
    evolveSuccess: '{name} 进化成了 {target}！',
    cannotEvolve: '这只宝可梦目前无法进化。',
    selectToEvolve: '选择一只宝可梦进行进化',
    chooseEvolution: '选择进化形态',
    evolve: '进化',
    shop: '商店',
    price: '价格',
    learningNewMove: '正在学习新技能...',
    learnThisMove: '学习此技能',
    noMoreMoves: '这只宝可梦暂时没有更多可学习的技能了。',
    reselectPokemon: '重新选择宝可梦',
    challengeEnd: '挑战结束',
    fellAtStage: '你在第 {stage} 关倒下了',
    restart: '重新开始',
    weather_none: '天气：无',
    weather_sunny: '天气：大晴天',
    weather_rainy: '天气：下雨',
    weather_sandstorm: '天气：沙暴',
    weather_hail: '天气：冰雹',
    weather_sunny_effect: '阳光增强了火属性技能，削弱了水属性技能。',
    weather_rainy_effect: '降雨增强了水属性技能，削弱了火属性技能。',
    weather_sandstorm_effect: '沙暴正在肆虐！岩石、地面和钢属性以外的宝可梦会受到伤害。',
    weather_hail_effect: '冰雹正在降下！冰属性以外的宝可梦会受到伤害。',
    reroll: '重新选择',
    rerollCost: '消耗 {cost} 金币',
    reachedFloor: '你在第 {stage} 关倒下了',
    gameOver: '挑战结束',
    factorySelect: '对战工厂：租赁宝可梦',
    factorySelectDesc: '从以下6只宝可梦中选择3只作为你的初始队伍。',
    factorySwap: '对战工厂：交换宝可梦',
    factorySwapDesc: '你可以选择一只自己的宝可梦与对手的一只进行交换。',
    confirmSelection: '确认选择 ({count}/3)',
    skipSwap: '跳过交换',
    swapWith: '交换',
    currentTeam: '当前队伍',
    opponentTeam: '对手队伍',
    streak: '连胜数: {count}',
    battleSettlementWin: '战斗胜利！当前连胜 {streak}，获得 {coins} 代币。',
    battleSettlementLoss: '战斗失败！仍获得 {coins} 代币。',
    battleResultWin: '本场胜利',
    battleResultLoss: '本场失败',
    tokensEarned: '获得代币：+{coins}',
    setProgress: '组别进度：{current}/{total}',
    setCompleted: '完成一组挑战！已击败第 7 战对手。',
    continueToSwap: '前往换怪',
    restartFactory: '返回开始',
    swapCount: '交换次数: {count}',
    enemyAiTier: '敌方 AI 档位: {tier}',
    cannotCatchFactory: '对战工厂内不可捕捉宝可梦。',
    playerSentOut: '你派出了 {name}！',
    enemySentOut: '对手 派出了 {name}！',
  },
  'zh-hant': {
    stage: '關卡',
    switch: '出戰',
    info: '詳情',
    selectMove: '選擇技能',
    back: '返回',
    victory: '勝利！',
    chooseReward: '選擇一項獎勵以繼續你的冒險',
    viewTeam: '查看我的隊伍',
    randomRewards: '隨機獎勵',
    getItem: '獲得道具',
    learnMove: '學習新技能',
    learnMoveDesc: '讓隊伍中的一隻寶可夢學習一個新技能',
    evolutionReward: '寶可夢進化',
    evolutionRewardDesc: '讓隊伍中的一隻寶可夢進化到下一階段',
    specialReward: '特殊獎勵',
    joinTeam: '加入隊伍',
    selectThis: '選擇此項',
    mysteryShop: '神秘商店 (使用金幣購買)',
    insufficientCoins: '金幣不足',
    buyItem: '購買道具',
    teamFull: '隊伍已滿！',
    replacePartner: '選擇一隻寶可夢進行替換，以加入新的夥伴',
    power: '威力',
    accuracy: '命中',
    pp: 'PP',
    nature: '性格',
    ability: '特性',
    none: '無',
    stats: '能力值',
    currentMoves: '當前技能',
    base: '種族',
    iv: '個體',
    physical: '物理',
    special: '特攻',
    status: '變化',
    confirm: '確認',
    cancel: '取消',
    battleLog: '戰鬥記錄',
    hp: 'HP',
    attack: '攻擊',
    defense: '防禦',
    spAtk: '特攻',
    spDef: '特防',
    speed: '速度',
    catchSuccess: '捕捉成功！獲得了 {coins} 金幣！',
    battleVictory: '戰鬥勝利！獲得了 {coins} 金幣！',
    selectToLearn: '選擇一隻寶可夢來學習新的力量',
    retrievingMoves: '正在檢索可學習的技能...',
    replaceWhichMove: '替換哪個技能？',
    alreadyKnows4: '{name} 已經學會了4個技能。',
    selectOldToReplace: '請選擇一個舊技能來替換為 {move}。',
    movesCount: '{count}/4 技能',
    learnMoveBtn: '學習技能',
    cancelReplace: '取消替換',
    searchingPokemon: '正在尋找寶可夢...',
    battleHistory: '對戰歷史',
    chooseStarter: '選擇你的初始夥伴',
    chooseStarterDesc: '從這三隻隨機寶可夢中選擇一隻開始你的冒險',
    startingMoves: '初始技能',
    viewDetails: '查看詳情',
    iChooseYou: '就決定是你了！',
    gymLeaderSent: '道館館主 派出了 {name}！',
    wildPokemonAppeared: '野生的 {name} 出現了！',
    youUsed: '你使用了 {name}！',
    cannotCatchGym: '不能捕捉道館館主的寶可夢！',
    catching: '正在捕捉...',
    catchSuccessMsg: '成功捕捉了 {name}！',
    joinedTeam: '{name} 已加入你的隊伍！',
    brokeFree: '{name} 掙脫了！',
    withdrew: '你收回了 {name}！',
    sentOut: '你派出了 {name}！',
    usedMove: '{name} 使用了 {move}！',
    superEffective: '這一擊效果絕佳！',
    notVeryEffective: '這一擊收效甚微...',
    noEffect: '似乎沒有效果...',
    causedDamage: '{name} 造成了 {damage} 點傷害。',
    fainted: '{name} 倒下了！',
    enemyUsedMove: '對手的 {name} 使用了 {move}！',
    enemyCausedDamage: '對手的 {name} 造成了 {damage} 點傷害。',
    noRecords: '尚無記錄',
    rogueJourney: 'PokeFactory 之旅：在無盡的挑戰中生存',
    startBattle: '開始對戰',
    selectRegion: '選擇你的冒險地區',
    nextStep: '下一步：選擇等級',
    setDifficulty: '設定初始挑戰難度',
    startAdventure: '開啟冒險之旅',
    thinking: '對手正在思考...',
    commandPhase: '指令階段',
    whatToDo: '該怎麼辦呢？',
    atkUp: '攻擊↑',
    defUp: '防禦↑',
    battle: '戰鬥',
    bag: '背包',
    pokemon: '寶可夢',
    run: '逃跑',
    myBag: '我的背包',
    myTeam: '我的隊伍',
    bagEmpty: '背包空空如也',
    backToMoves: '返回選擇技能',
    evolution: '進化',
    evolveSuccess: '{name} 進化成了 {target}！',
    cannotEvolve: '這隻寶可夢目前無法進化。',
    selectToEvolve: '選擇一隻寶可夢進行進化',
    chooseEvolution: '選擇進化形態',
    evolve: '進化',
    shop: '商店',
    price: '價格',
    learningNewMove: '正在學習新技能...',
    learnThisMove: '學習此技能',
    noMoreMoves: '這隻寶可夢暫時沒有更多可學習的技能了。',
    reselectPokemon: '重新選擇寶可夢',
    challengeEnd: '挑戰結束',
    fellAtStage: '你在第 {stage} 關倒下了',
    restart: '重新開始',
    weather_none: '天氣：無',
    weather_sunny: '天氣：大晴天',
    weather_rainy: '天氣：下雨',
    weather_sandstorm: '天氣：沙暴',
    weather_hail: '天氣：冰雹',
    weather_sunny_effect: '陽光增強了火屬性技能，削弱了水屬性技能。',
    weather_rainy_effect: '降雨增強了水屬性技能，削弱了火屬性技能。',
    weather_sandstorm_effect: '沙暴正在肆虐！岩石、地面和鋼屬性以外的寶可夢會受到傷害。',
    weather_hail_effect: '冰雹正在降下！冰屬性以外的寶可夢會受到傷害。',
    reroll: '重新選擇',
    rerollCost: '消耗 {cost} 點金幣',
    reachedFloor: '你在第 {stage} 關倒下了',
    gameOver: '挑戰結束',
    factorySelect: '對戰工廠：租賃寶可夢',
    factorySelectDesc: '從以下6隻寶可夢中選擇3隻作為你的初始隊伍。',
    factorySwap: '對戰工廠：交換寶可夢',
    factorySwapDesc: '你可以選擇一隻自己的寶可夢與對手的一隻進行交換。',
    confirmSelection: '確認選擇 ({count}/3)',
    skipSwap: '跳過交換',
    swapWith: '交換',
    currentTeam: '當前隊伍',
    opponentTeam: '對手隊伍',
    streak: '連勝數: {count}',
    battleSettlementWin: '戰鬥勝利！目前連勝 {streak}，獲得 {coins} 代幣。',
    battleSettlementLoss: '戰鬥失敗！仍獲得 {coins} 代幣。',
    battleResultWin: '本場勝利',
    battleResultLoss: '本場失敗',
    tokensEarned: '獲得代幣：+{coins}',
    setProgress: '組別進度：{current}/{total}',
    setCompleted: '完成一組挑戰！已擊敗第 7 戰對手。',
    continueToSwap: '前往換怪',
    restartFactory: '返回開始',
    swapCount: '交換次數: {count}',
    enemyAiTier: '敵方 AI 檔位: {tier}',
    cannotCatchFactory: '對戰工廠內不可捕捉寶可夢。',
    playerSentOut: '你派出了 {name}！',
    enemySentOut: '對手 派出了 {name}！',
  },
  'en': {
    stage: 'Stage',
    switch: 'Switch',
    info: 'Info',
    selectMove: 'Select Move',
    back: 'Back',
    victory: 'Victory!',
    chooseReward: 'Choose a reward to continue your adventure',
    viewTeam: 'View My Team',
    randomRewards: 'Random Rewards',
    getItem: 'Get Item',
    learnMove: 'Learn New Move',
    learnMoveDesc: 'Let a Pokemon in your team learn a new move',
    evolutionReward: 'Pokemon Evolution',
    evolutionRewardDesc: 'Let a Pokemon in your team evolve to the next stage',
    specialReward: 'Special Reward',
    joinTeam: 'Join Team',
    selectThis: 'Select This',
    mysteryShop: 'Mystery Shop (Buy with Coins)',
    insufficientCoins: 'Insufficient Coins',
    buyItem: 'Buy Item',
    teamFull: 'Team Full!',
    replacePartner: 'Select a Pokemon to replace with the new partner',
    power: 'Power',
    accuracy: 'Accuracy',
    pp: 'PP',
    nature: 'Nature',
    ability: 'Ability',
    none: 'None',
    stats: 'Stats',
    currentMoves: 'Current Moves',
    base: 'Base',
    iv: 'IV',
    physical: 'Physical',
    special: 'Special',
    status: 'Status',
    confirm: 'Confirm',
    cancel: 'Cancel',
    battleLog: 'Battle Log',
    hp: 'HP',
    attack: 'Attack',
    defense: 'Defense',
    spAtk: 'Sp. Atk',
    spDef: 'Sp. Def',
    speed: 'Speed',
    catchSuccess: 'Caught successfully! Earned {coins} coins!',
    battleVictory: 'Victory! Earned {coins} coins!',
    selectToLearn: 'Select a Pokemon to learn new power',
    retrievingMoves: 'Retrieving learnable moves...',
    replaceWhichMove: 'Replace which move?',
    alreadyKnows4: '{name} already knows 4 moves.',
    selectOldToReplace: 'Please select an old move to replace with {move}.',
    movesCount: '{count}/4 Moves',
    learnMoveBtn: 'Learn Move',
    cancelReplace: 'Cancel',
    searchingPokemon: 'Searching for Pokemon...',
    battleHistory: 'Battle History',
    chooseStarter: 'Choose Your Starter',
    chooseStarterDesc: 'Choose one of these three random Pokemon to start your adventure',
    startingMoves: 'Starting Moves',
    viewDetails: 'View Details',
    iChooseYou: 'I choose you!',
    gymLeaderSent: 'Gym Leader sent out {name}!',
    wildPokemonAppeared: 'A wild {name} appeared!',
    youUsed: 'You used {name}!',
    cannotCatchGym: 'Cannot catch Gym Leader\'s Pokemon!',
    catching: 'Catching...',
    catchSuccessMsg: 'Caught {name} successfully!',
    joinedTeam: '{name} joined your team!',
    brokeFree: '{name} broke free!',
    withdrew: 'You withdrew {name}!',
    sentOut: 'You sent out {name}!',
    usedMove: '{name} used {move}!',
    superEffective: 'It\'s super effective!',
    notVeryEffective: 'It\'s not very effective...',
    noEffect: 'It had no effect...',
    causedDamage: '{name} caused {damage} damage.',
    fainted: '{name} fainted!',
    enemyUsedMove: 'Enemy {name} used {move}!',
    enemyCausedDamage: 'Enemy {name} caused {damage} damage.',
    noRecords: 'No records',
    rogueJourney: 'PokeFactory Journey: Survive in endless challenges',
    startBattle: 'Start Battle',
    selectRegion: 'Select Your Region',
    nextStep: 'Next: Select Level',
    setDifficulty: 'Set Initial Difficulty',
    startAdventure: 'Start Adventure',
    thinking: 'Enemy is thinking...',
    commandPhase: 'Command Phase',
    whatToDo: 'What will you do?',
    atkUp: 'Atk↑',
    defUp: 'Def↑',
    battle: 'Battle',
    bag: 'Bag',
    pokemon: 'Pokemon',
    run: 'Run',
    myBag: 'My Bag',
    myTeam: 'My Team',
    bagEmpty: 'Bag is empty',
    backToMoves: 'Back to Moves',
    evolution: 'Evolution',
    evolveSuccess: '{name} evolved into {target}!',
    cannotEvolve: 'This Pokemon cannot evolve at this time.',
    selectToEvolve: 'Select a Pokemon to evolve',
    chooseEvolution: 'Choose Evolution Form',
    evolve: 'Evolve',
    shop: 'Shop',
    price: 'Price',
    learningNewMove: 'Learning new move...',
    learnThisMove: 'Learn this move',
    noMoreMoves: 'This Pokemon has no more learnable moves for now.',
    reselectPokemon: 'Reselect Pokemon',
    challengeEnd: 'Challenge Ended',
    fellAtStage: 'You fell at Stage {stage}',
    restart: 'Restart',
    weather_none: 'Weather: None',
    weather_sunny: 'Weather: Sunny',
    weather_rainy: 'Weather: Rainy',
    weather_sandstorm: 'Weather: Sandstorm',
    weather_hail: 'Weather: Hail',
    weather_sunny_effect: 'The sunlight is strong! Fire moves are boosted, Water moves are weakened.',
    weather_rainy_effect: 'It is raining! Water moves are boosted, Fire moves are weakened.',
    weather_sandstorm_effect: 'A sandstorm is raging! Non-Rock/Ground/Steel Pokemon take damage.',
    weather_hail_effect: 'Hail is falling! Non-Ice Pokemon take damage.',
    reroll: 'Reroll',
    rerollCost: 'Cost {cost} Coins',
    reachedFloor: 'You reached floor {stage}',
    gameOver: 'GAME OVER',
    factorySelect: 'Battle Factory: Rent Pokemon',
    factorySelectDesc: 'Choose 3 Pokemon from the 6 available to start your challenge.',
    factorySwap: 'Battle Factory: Swap Pokemon',
    factorySwapDesc: 'You can swap one of your Pokemon with one of your opponent\'s.',
    confirmSelection: 'Confirm Selection ({count}/3)',
    skipSwap: 'Skip Swap',
    swapWith: 'Swap',
    currentTeam: 'Current Team',
    opponentTeam: 'Opponent Team',
    streak: 'Streak: {count}',
    battleSettlementWin: 'Victory! Streak {streak}. Earned {coins} tokens.',
    battleSettlementLoss: 'Defeat. You still earned {coins} tokens.',
    battleResultWin: 'Battle Won',
    battleResultLoss: 'Battle Lost',
    tokensEarned: 'Tokens earned: +{coins}',
    setProgress: 'Set progress: {current}/{total}',
    setCompleted: 'Set completed! Boss defeated.',
    continueToSwap: 'Continue to Swap',
    restartFactory: 'Back to Start',
    swapCount: 'Swaps: {count}',
    enemyAiTier: 'Enemy AI Tier: {tier}',
    cannotCatchFactory: 'Catching is disabled in Battle Factory.',
    playerSentOut: 'You sent out {name}!',
    enemySentOut: 'Opponent sent out {name}!',
    specialTrigger: 'Special Trigger',
    specialTriggerHint: 'Choose Mega / Dynamax / Tera / Z-Move',
    specialLocked: 'Locked (Defeat Stage 21 Boss)',
    specialUsed: 'Special Used This Battle',
    specialMegaUsed: 'Mega Used',
    specialDynamaxUsed: 'Dynamax Used',
    specialTeraUsed: 'Tera Used',
    specialZMoveUsed: 'Z-Move Used',
    specialModeReady: 'Special Mode Ready',
    specialModeLocked: 'Special Mode Locked',
    specialBossBattle: 'Special Unlock Boss',
    specialUseMenuHint: 'Use Mega / Dynamax / Tera / Z-Move buttons to activate these items.',
    specialMegaStoneMismatch: 'Mega activation failed: current Pokemon is not holding a matching Mega stone.',
    specialZCrystalMismatch: 'Z-Move activation failed: current Pokemon is not holding a matching Z-Crystal.',
    specialDynamaxEnd: '{name} returned to normal size.',
    specialActivated: '{name} activated {mode}!',
    enemySpecialActivated: 'Enemy {name} activated {mode}!',
    specialModeUnlock: 'Special trigger mode unlocked! You can now activate one special trigger per battle.',
    specialUnlockBossIntro: 'Special Boss Challenge! Defeat this opponent to unlock global special triggers.',
    specialMega: 'Mega Evolution',
    specialDynamax: 'Dynamax Sync',
    specialTera: 'Terastal Shift',
    specialZMove: 'Z-Move Burst',
    specialBurst: 'Battle Burst',
  }
};

Object.assign(uiStrings.en, {
  bootTitle: 'System Startup',
  bootDesc: 'Load required data before entering Base.',
  bootPreparingRentalPool: 'Preparing rental pool...',
  bootPreparingEnemyPreview: 'Preparing enemy preview...',
  bootPreparingPokedexIndex: 'Preparing Pokedex index...',
  bootPreparingDexSnapshots: 'Preparing Pokedex snapshots...',
  bootPreparingMoveIndex: 'Preparing move index...',
  bootFinalizingStartup: 'Finalizing startup...',
  bootReady: 'Ready',
  bootLoadingWait: 'Professor is still untangling a very angry cable of Magnemite.',
  bootLoadingReady: 'All set. Your partner is already waiting at the gate.',
  bootEnterBase: 'Enter Base',
  bootFlavor1: 'Rotom is negotiating with the power grid...',
  bootFlavor2: 'Machamp is carrying servers one-handed.',
  bootFlavor3: 'Snorlax blocked the data lane. Politely nudging...',
  bootFlavor4: 'Porygon is sorting files by cuteness level.',
  bootFlavor5: 'Lucario sensed stable aura. Almost done.',
  bootFlavor6: 'Nurse Joy approved the startup checkup.',
  bootFlavor7: 'Metagross is optimizing in four dimensions.',
  bootFlavor8: 'Gengar hid one file. We asked nicely.',
  bootFlavor9: 'Lapras delivered backups across the sea.',
  bootFlavor10: 'Dragonite arrived with the final package.',
  bootFlavor11: 'Pikachu charged the backup batteries.',
  bootFlavor12: 'Alakazam predicted all loading errors.',
  bootFlavor13: 'Blastoise pressure-washed dusty modules.',
  bootFlavor14: 'Eevee is deciding what this app should evolve into.',
  bootFlavor15: 'Mimikyu insisted on quality assurance.',
  bootFlavor16: 'Ditto copied the config. Twice.',
  bootFlavorReady: 'Pokeballs polished. Arena lights on.',
});

Object.assign(uiStrings['zh-hans'], {
  bootTitle: '系统启动',
  bootDesc: '加载核心数据后进入基地。',
  bootPreparingRentalPool: '正在预载租赁池...',
  bootPreparingEnemyPreview: '正在预载敌方预览...',
  bootPreparingPokedexIndex: '正在预载图鉴索引...',
  bootPreparingDexSnapshots: '正在预载图鉴快照...',
  bootPreparingMoveIndex: '正在预载技能索引...',
  bootFinalizingStartup: '正在完成启动...',
  bootReady: '准备就绪',
  bootLoadingWait: '博士还在解开一团生气的小磁怪电缆。',
  bootLoadingReady: '准备完成，你的搭档已经在门口等你了。',
  bootEnterBase: '进入基地',
  bootFlavor1: '洛托姆正在和电网谈判中...',
  bootFlavor2: '怪力单手搬服务器，效率惊人。',
  bootFlavor3: '卡比兽堵住数据通道，正在温柔劝离。',
  bootFlavor4: '多边兽按“可爱等级”整理档案。',
  bootFlavor5: '路卡利欧感应到波导稳定，快好了。',
  bootFlavor6: '乔伊小姐已通过启动体检。',
  bootFlavor7: '巨金怪正在进行四维优化。',
  bootFlavor8: '耿鬼藏起了一份文件，正在友好协商。',
  bootFlavor9: '拉普拉斯已把备份跨海送达。',
  bootFlavor10: '快龙带着最后一包数据抵达。',
  bootFlavor11: '皮卡丘给备用电池补满了电。',
  bootFlavor12: '胡地已经预判了所有报错。',
  bootFlavor13: '水箭龟把积灰模块都冲洗干净了。',
  bootFlavor14: '伊布还在思考这套系统该进化成什么。',
  bootFlavor15: '谜拟Q坚持要做质量验收。',
  bootFlavor16: '百变怪把配置复制了两份。',
  bootFlavorReady: '精灵球擦亮完毕，对战灯光就绪。',
});

Object.assign(uiStrings['zh-hant'], {
  bootTitle: '系統啟動',
  bootDesc: '載入核心資料後進入基地。',
  bootPreparingRentalPool: '正在預載租賃池...',
  bootPreparingEnemyPreview: '正在預載敵方預覽...',
  bootPreparingPokedexIndex: '正在預載圖鑑索引...',
  bootPreparingDexSnapshots: '正在預載圖鑑快照...',
  bootPreparingMoveIndex: '正在預載技能索引...',
  bootFinalizingStartup: '正在完成啟動...',
  bootReady: '準備就緒',
  bootLoadingWait: '博士還在解開一團生氣的小磁怪電纜。',
  bootLoadingReady: '準備完成，你的夥伴已經在門口等你了。',
  bootEnterBase: '進入基地',
  bootFlavor1: '洛托姆正在和電網談判中...',
  bootFlavor2: '怪力單手搬伺服器，效率驚人。',
  bootFlavor3: '卡比獸堵住資料通道，正在溫柔勸離。',
  bootFlavor4: '多邊獸按「可愛等級」整理檔案。',
  bootFlavor5: '路卡利歐感應到波導穩定，快好了。',
  bootFlavor6: '喬伊小姐已通過啟動體檢。',
  bootFlavor7: '巨金怪正在進行四維最佳化。',
  bootFlavor8: '耿鬼藏起一份檔案，正在友好協商。',
  bootFlavor9: '拉普拉斯已把備份跨海送達。',
  bootFlavor10: '快龍帶著最後一包資料抵達。',
  bootFlavor11: '皮卡丘把備用電池充滿了電。',
  bootFlavor12: '胡地已預判所有報錯。',
  bootFlavor13: '水箭龜把積灰模組都沖洗乾淨了。',
  bootFlavor14: '伊布還在思考這套系統該進化成什麼。',
  bootFlavor15: '謎擬Q堅持要做品質驗收。',
  bootFlavor16: '百變怪把設定複製了兩份。',
  bootFlavorReady: '精靈球擦亮完畢，對戰燈光就緒。',
});

export default uiStrings;
